# Generated by Django 3.0.7 on 2020-06-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='name',
            field=models.CharField(default='Mysite', max_length=255),
            preserve_default=False,
        ),
    ]
