# Generated by Django 3.0.7 on 2020-06-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='domain',
            field=models.CharField(default='example.com', max_length=255),
            preserve_default=False,
        ),
    ]
